version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: realestate-postgres
    environment:
      POSTGRES_DB: real_estate_db
      POSTGRES_USER: realestate_user
      POSTGRES_PASSWORD: realestate_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realestate_user -d real_estate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: